### ISSUE TITLE
Difficulty in Styling chakra-ui-file-picker Component

### ISSUE THREAD

**Issue by bonface221** [PedroDBFlores/chakra-ui-file-picker#1]
I am using the chakra-ui-file-picker component in my project to create a file input. While the component works well for basic use cases, I am facing difficulty in styling the component to match my application's design.

I have tried using Chakra UI's style props and other customization options, but the component seems to have limited support for styling. This is causing inconsistencies in the appearance of my application, and I am unable to achieve the desired look and feel.

I would appreciate it if you could look into this issue and provide a solution or enhancement to the component that allows for better customization and styling options. This would greatly improve the developer experience and make it easier to integrate the chakra-ui-file-picker component into various projects.

Thank you for your attention to this matter.

**Comment by PedroDBFlores** [comment]
So what I have done is put those props on the component:

` inputProps?: InputGroupProps
    inputGroupProps?: InputGroupProps
    buttonProps?: ButtonProps
`

So you can style this components in a separate way. Is this not working for you?

**Comment by bonface221** [comment]
Thanks 😊
